services:
  db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: lazybook
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lazybookdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - db

volumes:
  pgdata:
